### ISSUE TITLE
Suggested enhancement

### ISSUE THREAD

**Issue by Morganizer** [cluther/zendev-scripts#1]
from your MD file:

"zp cdr HttpMonitor<tab>

Changes to the root directory of a ZenPack. This is really only useful because it contains the setup.py file that you occasionally need to modify."

If the above is true, how about something like:

"zp visetup HttpMonitor<tab>

Open the setup.py file of the specified Zenpack for editing (without changing directory)."

Of course, you wouldn't remove the existing switch, but this would reduce steps.

**Comment by cluther** [comment]
@Morganizer: Sounds like a good idea to me. I added it.
